name: Dockerhub Login

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: echo "dckr_pat_zMD1wQwTx4E27pdYKBre0aiVUkU" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
